name: pull_on_loading
description: Pull up load more,pull down refresh

dependencies:
  flutter:
    sdk: flutter
  http: ^0.12.0+1
  cupertino_icons: ^0.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

